spring.application.name: kafka-stream-poc
server.port: 8080

logging.level:
  org.springframework: INFO
  com.abshekh: DEBUG

spring.cloud.stream.bindings:
  topicConsumer-in-0:
    destination: topic1
    group: topic-consumer-group-1
  topicProducer-out-0:
    destination: topic1
  topic2Consumer-in-0:
    destination: topic2
    group: topic2-consumer-group-1
  topic2Producer-out-0:
    destination: topic2
  topic3Consumer-in-0:
    destination: topic3
    group: topic3-consumer-group-1
  topic3Producer-out-0:
    destination: topic3
  topic4Consumer-in-0:
    destination: topic4
    group: topic4-consumer-group-1
  topic4Producer-out-0:
    destination: topic4

spring.cloud.stream:
  function.definition: topicConsumer;topic2Consumer;topic3Consumer;topic4Consumer;
  kafka.streams:
    bindings:
      topicConsumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topicConsumer
      topic2Consumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topic2Consumer
      topic3Consumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topic3Consumer
      topic4Consumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topic4Consumer
    binder:
      configuration:
        commit.interval.ms: 1000
        processing.guarantee: exactly_once_v2
      deserializationExceptionHandler: logAndContinue
